// <auto-generated />
using System;
using ClinicsRate.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClinicsRate.Migrations
{
    [DbContext(typeof(ClinicRateDbContext))]
    [Migration("20181220170600_UzupelnienieTabeliUser")]
    partial class UzupelnienieTabeliUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClinicsRate.Models.Clinic", b =>
                {
                    b.Property<int>("ClinicId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<string>("ClinicName");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PostCode");

                    b.Property<int>("ProvinceId");

                    b.Property<string>("Street");

                    b.HasKey("ClinicId");

                    b.HasIndex("CityId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("ClinicsRate.Models.ClinicTMP", b =>
                {
                    b.Property<int>("ClinicId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<string>("ClinicName");

                    b.Property<int?>("DictCityId");

                    b.Property<int?>("DictProvinceId");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PostCode");

                    b.Property<int>("ProvinceId");

                    b.Property<string>("Street");

                    b.HasKey("ClinicId");

                    b.HasIndex("DictCityId");

                    b.HasIndex("DictProvinceId");

                    b.ToTable("ClinicsTMP");
                });

            modelBuilder.Entity("ClinicsRate.Models.DictCity", b =>
                {
                    b.Property<int>("DictCityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("DictCityId");

                    b.ToTable("DictCities");
                });

            modelBuilder.Entity("ClinicsRate.Models.DictProvince", b =>
                {
                    b.Property<int>("DictProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("DictProvinceId");

                    b.ToTable("DictProvinces");
                });

            modelBuilder.Entity("ClinicsRate.Models.Opinion", b =>
                {
                    b.Property<int>("OpinionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClinicId");

                    b.Property<string>("Description");

                    b.Property<int>("Rate");

                    b.Property<int?>("UserId");

                    b.Property<string>("Username");

                    b.HasKey("OpinionId");

                    b.HasIndex("ClinicId");

                    b.HasIndex("UserId");

                    b.ToTable("Opinions");
                });

            modelBuilder.Entity("ClinicsRate.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessLevel");

                    b.Property<string>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("getdate()");

                    b.Property<int>("Deleted");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ClinicsRate.Models.Clinic", b =>
                {
                    b.HasOne("ClinicsRate.Models.DictCity", "DictCity")
                        .WithMany("Clinics")
                        .HasForeignKey("CityId");

                    b.HasOne("ClinicsRate.Models.DictProvince", "DictProvince")
                        .WithMany("Clinics")
                        .HasForeignKey("ProvinceId");
                });

            modelBuilder.Entity("ClinicsRate.Models.ClinicTMP", b =>
                {
                    b.HasOne("ClinicsRate.Models.DictCity", "DictCity")
                        .WithMany()
                        .HasForeignKey("DictCityId");

                    b.HasOne("ClinicsRate.Models.DictProvince", "DictProvince")
                        .WithMany()
                        .HasForeignKey("DictProvinceId");
                });

            modelBuilder.Entity("ClinicsRate.Models.Opinion", b =>
                {
                    b.HasOne("ClinicsRate.Models.Clinic", "Clinic")
                        .WithMany("Opinions")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClinicsRate.Models.User", "User")
                        .WithMany("Opinions")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
